### ISSUE TITLE
Connection reset when using http

### ISSUE THREAD

**Issue by unlocomqx** [GoogleChromeLabs/simplehttp2server#33]
I'm on a windows 10 x64 machine and I'm using sh2sv 
When I fire lighthouse it fails when testing http > https redirect with ERR_CONNECTION_RESET
When I visit http://localhost:8080, my console shows multiple errors similar to this:

http: TLS handshake error from [::1]:59634: read tcp [::1]:8080->[::1]:59XXX: use of closed network connection

Is this a known issue? What should I update?

Thank you

**Comment by surma** [comment]
It’s not a “real” issue. It stems from the fact than I added [a bit of code](https://github.com/GoogleChrome/simplehttp2server/blob/b263e8181ec51e3ac566058aa99f3efc26b3ce10/httpsdetect.go#L39-L70) when you connect to the TLS-enabled server over `http://` (instead of `https://`). I hijack the connection and issue a redirect to `https://`, but the HTTP server stumbles a bit over the state of the connection thereafter.

It’s safe to ignore and “working as expected”, but I’ll see if I can be a bit cleaner about this and not have errors :)

**Comment by unlocomqx** [comment]
Yeah I see it's basically returning a closed connection
As you said, it's not a real issue but lighthouse doesn't like it

**Comment by tnunes** [comment]
Just adding that I just bumped into this issue when using the latest Chrome stable (70.0.3538.102) and canary (72.0.3612.0).

Chrome gets a `ERR_CONNECTION_RESET` error and `simplehttp2server` logs this into the console:

```2018/11/16 21:10:01 Listening on https://localhost:5000...
^[^[^[2018/11/16 21:10:08 http: TLS handshake error from [::1]:63343: read tcp [::1]:5000->[::1]:63343: use of closed network connection
2018/11/16 21:10:09 http: TLS handshake error from [::1]:63346: read tcp [::1]:5000->[::1]:63346: use of closed network connection
2018/11/16 21:10:14 http: TLS handshake error from [::1]:63347: read tcp [::1]:5000->[::1]:63347: use of closed network connection```

Found the issue because this is causing the lighthouse PWA checks about the HTTP->HTTPS redirect and `<noscript />` content to fail, as previously mentioned in related issues.

I'm using the latest version from this repo, installed through a brew tap (stable 3.1.3).
